"""message

Revision ID: 6f548b32999c
Revises: 605a365da42f
Create Date: 2025-04-26 21:29:52.807748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f548b32999c'
down_revision = '605a365da42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collect')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='collect_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='collect_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
